version: '2'
services:
  api:
    build:
      context: .
      dockerfile: docker/development/Dockerfile
    image: ${API_NAME}
    command: make dev 
    ports:
      - 8080:3030
    volumes:
      - .:/go/src/gin-api-boilerplate
    depends_on:
      - db
      - redis
  db:
    image: mongo:4.0.2-xenial
    ports:
      - 27017:27017
    volumes:
      - ./docker/development/mongo-init/:/docker-entrypoint-initdb.d/
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - APP_MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_ROOT_USER=${MONGO_ROOT_USERNAME}
      - MONGO_ROOT_PASS=${MONGO_ROOT_PASSWORD}
      - APP_MONGO_USER=${APP_MONGO_USER}
      - APP_MONGO_PASS=${APP_MONGO_PASS}
      - APP_MONGO_DB=${APP_MONGO_DB}
  redis:
    image: redis:4-alpine
    volumes:
      - ./data/config/redis.conf:/usr/local/etc/redis/redis.conf
      - ./data/redis:/data
    ports:
      - 6379:6379
    command: redis-server /usr/local/etc/redis/redis.conf
